version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 100
    reviewers:
    - berviantoleo
    assignees:
    - berviantoleo
