name: "Security Check"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '30 1 * * 6'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Static Analysis use Sobelow
      uses: sobelow/action@v1
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
